builds:
  - binary: moco
    goos:
      - darwin
      - linux
    goarch:
      - arm64
      - amd64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: moco-cli
    homepage: "https://github.com/foobaragency/moco-cli"
    download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
    repository:
      owner: foobaragency  
      name: homebrew-foobaragency

checksum:
  name_template: 'checksums.txt'
